Controllers/RentalRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using video_rental;
using video_rental.Models;

namespace video_rental.Controllers
{
    public class RentalRecordsController : Controller
    {
        private readonly video_rentalsContext _context;

        public RentalRecordsController(video_rentalsContext context)
        {
            _context = context;
        }

        // GET: RentalRecords
        public async Task<IActionResult> Index()
        {
            return View(await _context.RentalRecords.ToListAsync());
        }

        // GET: RentalRecords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalRecordsModel = await _context.RentalRecords
                .SingleOrDefaultAsync(m => m.RentalID == id);
            if (rentalRecordsModel == null)
            {
                return NotFound();
            }

            return View(rentalRecordsModel);
        }

        // GET: Check out movie
        public async Task<IActionResult> CheckOutMovie(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moviesModel = await _context.Movies
                .Include(m => m.GenresModel)
                .SingleOrDefaultAsync(m => m.MovieID == id);

            ViewData["customers"] = new SelectList(_context.Customers, "CustomerID", "CustomerName");

            if (moviesModel == null)
            {
                return NotFound();
            }

            return View(moviesModel);
        }


        //GET: RentalRecords/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> CheckInMovie(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

             var moviesModel = await _context.Movies
                .Include(m => m.GenresModel)
                .SingleOrDefaultAsync(m => m.MovieID == id);
            moviesModel.IsCheckedOut = false;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Movies");
        }

        //POST: RentalRecords/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,MovieID,DueDate")] RentalRecordsModel rentalRecordsModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rentalRecordsModel);
                var movie = await _context.Movies.SingleOrDefaultAsync(s => s.MovieID == rentalRecordsModel.MovieID);
                movie.IsCheckedOut = true;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rentalRecordsModel);
        }

        // public async Task<IActionResult> CheckOutMovie()
        // {

        // }

        // GET: RentalRecords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalRecordsModel = await _context.RentalRecords.SingleOrDefaultAsync(m => m.RentalID == id);
            if (rentalRecordsModel == null)
            {
                return NotFound();
            }
            return View(rentalRecordsModel);
        }

        // POST: RentalRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RentalID,CustomerID,CustomerName,MovieID,MovieTitle,DueDate,IsOverdue")] RentalRecordsModel rentalRecordsModel)
        {
            if (id != rentalRecordsModel.RentalID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rentalRecordsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalRecordsModelExists(rentalRecordsModel.RentalID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rentalRecordsModel);
        }

        // GET: RentalRecords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalRecordsModel = await _context.RentalRecords
                .SingleOrDefaultAsync(m => m.RentalID == id);
            if (rentalRecordsModel == null)
            {
                return NotFound();
            }

            return View(rentalRecordsModel);
        }

        // POST: RentalRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rentalRecordsModel = await _context.RentalRecords.SingleOrDefaultAsync(m => m.RentalID == id);
            _context.RentalRecords.Remove(rentalRecordsModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentalRecordsModelExists(int id)
        {
            return _context.RentalRecords.Any(e => e.RentalID == id);
        }
    }
}

Views/RentalRecords/CheckOutMovie.cshtml
@model video_rental.Models.MoviesModel

@{
    ViewData["Title"] = "Details";
}

<h2>Check out movie</h2>

<div>
    <h4>Check Out Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearReleased)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearReleased)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GenresModel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GenresModel.GenreName)
        </dd>
    </dl>
</div>

<div>
    @using (Html.BeginForm("Create", "RentalRecords"))
    {
        @Html.Hidden("MovieID")

        <select name="customerID" class ="form-control" asp-items="ViewBag.customers"></select>

        // Turn this into a date field
        <input name="DueDate" type="date"/>

        <input type="submit" name="Save" value="Save" />
    }
</div>

Views/RentalRecords/Create.cshtml
@model video_rental.Models.RentalRecordsModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>RentalRecordsModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <input asp-for="CustomerID" class="form-control" />
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <input asp-for="MovieID" class="form-control" />
                <span asp-validation-for="MovieID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieTitle" class="control-label"></label>
                <input asp-for="MovieTitle" class="form-control" />
                <span asp-validation-for="MovieTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsOverdue" /> @Html.DisplayNameFor(model => model.IsOverdue)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/RentalRecords/Delete.cshtml
@model video_rental.Models.RentalRecordsModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RentalRecordsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MovieID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsOverdue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsOverdue)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RentalID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/RentalRecords/Details.cshtml
@model video_rental.Models.RentalRecordsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>RentalRecordsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MovieID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsOverdue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsOverdue)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RentalID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/RentalRecords/Edit.cshtml
@model video_rental.Models.RentalRecordsModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>RentalRecordsModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RentalID" />
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <input asp-for="CustomerID" class="form-control" />
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <input asp-for="MovieID" class="form-control" />
                <span asp-validation-for="MovieID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieTitle" class="control-label"></label>
                <input asp-for="MovieTitle" class="form-control" />
                <span asp-validation-for="MovieTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsOverdue" /> @Html.DisplayNameFor(model => model.IsOverdue)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/RentalRecords/Index.cshtml
@model IEnumerable<video_rental.Models.RentalRecordsModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CustomerID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CustomerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MovieID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MovieTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DueDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsOverdue)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsOverdue)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RentalID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RentalID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RentalID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>